version: '3.8'

services:

  mongo:
    image: mongo:6.0.13
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./db_mongo:/data/db
    ports:
      - 27017:27017